{
  "language": "java",
  "jdk": "oraclejdk7",
  "notifications": {
    "email": false
  },
  "branches": {
    "excludes": [
      "gh-pages"
    ]
  },
  "env": "ANDROID_SDKS=sysimg-16            ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a",
  "before_install": [
    "echo yes | sudo apt-get update -qq",
    "if [ `uname -m` = x86_64 ]; then echo yes | sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi",
    "wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz",
    "tar xzf android-sdk_r21.0.1-linux.tgz",
    "export ANDROID_HOME=$PWD/android-sdk-linux",
    "export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools",
    "android update sdk --filter platform-tools,android-16,extra-android-support,$ANDROID_SDKS --no-ui --force",
    "echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI",
    "emulator -avd test -no-skin -no-audio -no-window &"
  ],
  "before_script": [
    "chmod u+x wait_for_emulator",
    "./wait_for_emulator"
  ],
  "script": "mvn install -Pintegration-tests -Dandroid.device=test",
  ".result": "configured"
}